"use client";
import {useState} from "react";
import {iaHeaders,items,type Item} from "./data";

const Badge=({text}:{text:string})=><span className={'badge '+(text.includes('완료')||text==='반영'?'green':text.includes('실패')||text.includes('필요')?'orange':'blue')}><i/>{text}</span>;
const Head=({tag,title,desc,children}:{tag:string;title:string;desc:string;children?:React.ReactNode})=><div className="heading"><div><small>{tag}</small><h1>{title}</h1><p>{desc}</p></div><div>{children}</div></div>;
export const calculateNextVersion=(latest:string)=>{const match=latest.match(/^v(\d+)\.(\d+)$/);if(!match)return "v1.0";const major=Number(match[1]),minor=Number(match[2]);return minor>=9?`v${major+1}.0`:`v${major}.${minor+1}`};
// VPUB-05: pure publish-version validation. Trim → empty is invalid; a value that
// duplicates an existing official version is invalid; otherwise valid. Free-form
// strings (incl. 3-part like "2.7.1") are accepted.
export const validatePublishVersion=(raw:string,existing:string[])=>{const value=(raw??'').trim();if(!value)return {ok:false as const,message:'버전 번호를 입력하세요.'};if(existing.some(v=>v.trim().toLowerCase()===value.toLowerCase()))return {ok:false as const,message:'이미 존재하는 공식 버전입니다: '+value};return {ok:true as const,value}};

export function HierarchyView({open}:{open:(item:Item)=>void}){
 const [expanded,setExpanded]=useState<string[]>(['1.탐색']);
 const [selected,setSelected]=useState('');
 const depths=[...new Set(items.map(x=>x.d1))];
 const toggle=(key:string)=>setExpanded(x=>x.includes(key)?x.filter(v=>v!==key):[...x,key]);
 return <><Head tag="HIERARCHY" title="SBF 계층 트리" desc="Depth 1~4 구조를 펼쳐 보고 선택한 노드의 업무를 확인합니다."/><div className="tree-layout"><section className="panel tree-panel"><div className="panel-title"><h2>업무 분류체계</h2><span>Depth 1만 기본 펼침</span></div>{depths.map(d1=><div className="tree-node" key={d1}><button className="tree-root" onClick={()=>toggle(d1)}><b>{expanded.includes(d1)?'⌄':'›'}</b><span>{d1}</span><em>{items.filter(x=>x.d1===d1).length}</em></button>{expanded.includes(d1)&&[...new Set(items.filter(x=>x.d1===d1).map(x=>x.d2))].map(d2=><div className="tree-branch" key={d2}><button onClick={()=>toggle(d1+d2)}><b>{expanded.includes(d1+d2)?'−':'+'}</b>{d2}</button>{expanded.includes(d1+d2)&&items.filter(x=>x.d1===d1&&x.d2===d2).map(x=><button key={x.id+'-'+x.sub} className={'tree-leaf '+(selected===x.id+'-'+x.sub?'active':'')} onClick={()=>setSelected(x.id+'-'+x.sub)}><span>{x.d3}</span><small>{x.id} · SUB {x.sub}</small></button>)}</div>)}</div>)}</section><section className="panel tree-results"><div className="panel-title"><h2>선택 노드 업무</h2><span>{selected?'1개':'노드를 선택하세요'}</span></div>{selected?items.filter(x=>x.id+'-'+x.sub===selected).map(x=><article key={selected}><Badge text={x.status}/><h3>{x.d3}</h3><p>{x.d1} › {x.d2} › {x.d3} › {x.d4}</p><dl><dt>업무ID</dt><dd>{x.id} · SUB {x.sub}</dd><dt>L3</dt><dd>{x.l3}</dd><dt>담당 분과</dt><dd>{x.squad}</dd></dl><button className="primary" onClick={()=>open(x)}>상세 정보 보기</button></article>):<div className="empty"><b>⌘</b><h3>계층 노드를 선택해 주세요</h3><p>선택한 업무와 하위 항목이 여기에 표시됩니다.</p></div>}</section></div></>;
}

export function ChangeCompare({request,masterRows=items,complete,onBack}:{request?:{id:string;title:string;type:string;requester:string;status:string;date:string;note?:string;targetBusinessId?:string;targetSubId?:number;afterRaw?:string[];beforeRaw?:string[]};masterRows?:Item[];complete?:(afterRaw:string[])=>void;onBack?:()=>void}){const current=request??{id:"CR-2026-0812-07",title:"청구계정 업무 Depth 조정",type:"Depth 조정",requester:"김서현",status:"SBF 반영 중",date:"2026-08-12",note:"SBF 반영 작업 진행 중",targetBusinessId:"B2036",targetSubId:1};const targetId=current.targetBusinessId||"B2036";const targetSub=current.targetSubId??1;const beforeItem=masterRows.find(x=>x.id===targetId&&x.sub===targetSub)??masterRows.find(x=>x.id===targetId)??items.find(x=>x.id==="B2036")??items[0];const beforeRaw=beforeItem.raw;const [afterRaw,setAfterRaw]=useState(()=>(current as any).afterRaw??(beforeRaw.map((v,i)=>i===7&&current.type.includes("Depth")?"청구·납부 계정 관리":v)));const editRaw=(index:number,value:string)=>setAfterRaw(x=>x.map((v,i)=>i===index?value:v));const changedCount=afterRaw.filter((v,i)=>v!==beforeRaw[i]).length;const goBack=()=>{if(!onBack)return;if(window.confirm("현재 작업된 내용은 저장되지 않습니다. 처리 업무 화면으로 돌아가시겠습니까?"))onBack()};return <><Head tag="SBF APPLY WORK" title="SBF 반영 작업" desc="승인된 변경요청의 대상 업무ID 기준 전체 IA 필드를 확인하고 SBF 마스터 반영 값을 직접 수정합니다."><button onClick={goBack}>{'돌아가기'}</button><button className="primary" onClick={()=>complete?.(afterRaw)} disabled={!complete||current.status==="SBF 반영 완료"}>{current.status==="SBF 반영 완료"?"반영 완료됨":"SBF 반영 완료"}</button></Head><div className="compare-summary panel"><div><span>요청번호</span><strong>{current.id}</strong></div><div><span>대상 업무ID</span><strong>{beforeItem.id} · SUB {beforeItem.sub}</strong></div><div><span>요청 제목</span><strong>{current.title}</strong></div><div><span>요청자</span><strong>{current.requester}</strong></div><div><span>변경 필드</span><strong>{changedCount}개</strong></div><Badge text={current.status}/></div><div className="apply-guide panel"><strong>SBF 수정 작업 기준</strong><p>변경 전은 현재 공식 SBF 버전의 전체 IA 필드이며 읽기 전용입니다. 변경 후는 작업본/template에 저장될 값을 직접 수정하는 영역입니다.</p></div><section className="panel full-field-compare"><div className="panel-title"><h2>업무ID별 전체 필드 변경 전/후</h2><span>{iaHeaders.length}개 컬럼 · 변경 후 직접 수정</span></div><div className="full-field-table"><table><thead><tr><th>컬럼</th><th>변경 전 · 공식 버전</th><th>변경 후 · 작업본/template</th></tr></thead><tbody>{iaHeaders.map((header,i)=><tr key={i} className={beforeRaw[i]!==afterRaw[i]?"changed":""}><td><strong>{header||String.fromCharCode(65+i)}</strong><small>{String.fromCharCode(65+i)}열</small></td><td>{beforeRaw[i]||"-"}</td><td><input aria-label={(header||String.fromCharCode(65+i))+" 변경 후"} value={afterRaw[i]??""} onChange={e=>editRaw(i,e.target.value)}/></td></tr>)}</tbody></table></div></section></>}
export function HistoryView(){const [type,setType]=useState('전체');return <><Head tag="AUDITABLE HISTORY" title="SBF 변경이력" desc="필드 단위 변경과 Jira 반영 여부를 시간순으로 추적합니다."></Head><div className="history-layout"><section className="panel history-table"><div className="filters"><label>⌕<input aria-label="변경이력 검색" placeholder="업무ID, 변경 내용 검색"/></label><select aria-label="변경 구분" value={type} onChange={e=>setType(e.target.value)}><option>전체</option><option>업무ID 변경</option><option>Depth 조정</option></select><input type="date" aria-label="시작일" defaultValue="2026-07-01"/><button>조회</button></div><table><thead><tr><th>일자</th><th>변경 구분</th><th>업무ID</th><th>Depth 1</th><th>Depth 2</th><th>Depth 3</th><th>처리자</th><th>Jira</th></tr></thead><tbody>{[['2026-07-15','업무ID 변경','BA451','상품','전략','CR 환경 및 경쟁사 분석','관리자 A','반영'],['2026-07-15','업무ID 변경','BA452','상품','전략','타겟 고객 도출','관리자 A','반영'],['2026-07-08','Depth 조정','B2036','고객','회원·계정','청구계정','관리자 B','미반영']].filter(x=>type==='전체'||x[1]===type).map(x=><tr key={x[2]}>{x.slice(0,7).map((v,i)=><td key={i}>{i===2?<button className="id">{v}</button>:v}</td>)}<td><Badge text={x[7]}/></td></tr>)}</tbody></table></section><aside className="panel timeline"><div className="panel-title"><h2>B2036 타임라인</h2><span>최근 50건</span></div>{[['2026-08-12 10:34','검토 시작','이도윤'],['2026-08-12 09:18','변경요청 접수','김서현'],['2026-07-08 15:42','v2.5 반영 완료','관리자 B']].map((x,i)=><div key={x[0]}><i className={i===0?'active':''}/><p><strong>{x[1]}</strong><small>{x[0]} · {x[2]}</small></p></div>)}</aside></div></>}

export function VersionView({versions,download,notify,pendingCount,nextVersion,defaultVersion,canPublish=false,importedThisSession=false,onPublish}:{versions:{version:string;date:string;owner:string;count:number;status:string}[];download:(v:string)=>void;notify:(x:string)=>void;pendingCount:number;nextVersion:string;defaultVersion?:string;canPublish?:boolean;importedThisSession?:boolean;onPublish:(version:string,reason:string)=>void}){
 const [publish,setPublish]=useState(false),[saving,setSaving]=useState(false);const latestOfficialVersion=versions[0]?.version??'v1.0';
 // VPUB-03: suggested default = version hint (defaultVersion) → calculateNextVersion fallback.
 const suggestedVersion=(defaultVersion&&defaultVersion.trim())||nextVersion;
 const [versionInput,setVersionInput]=useState(suggestedVersion),[versionError,setVersionError]=useState('');
 const openPublish=()=>{setVersionInput(suggestedVersion);setVersionError('');setPublish(true)};
 const publishVersion=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);const reason=String(data.get('reason')??'');
  // VPUB-05: block empty / duplicate version before publishing or downloading.
  const check=validatePublishVersion(versionInput,versions.map(v=>v.version));if(!check.ok){setVersionError(check.message);notify(check.message);return}
  setVersionError('');setSaving(true);setTimeout(()=>{onPublish(check.value,reason);setSaving(false);setPublish(false);notify(check.value+' 공식 SBF 버전을 배포했습니다. SBF 마스터 기본 버전이 '+check.value+'로 전환됩니다.')},350)};
 const blockEnterSubmit=(e:React.KeyboardEvent<HTMLFormElement>)=>{const t=e.target as HTMLElement;if(e.key==='Enter'&&t.tagName!=='TEXTAREA'&&t.tagName!=='BUTTON'&&(t as HTMLButtonElement).type!=='submit'){e.preventDefault()}};
 // VPUB-06: enable publish when there are workflow pending changes OR a session import replaced the active version.
 const publishable=canPublish||pendingCount>0;
 return <><Head tag="DEPLOYMENT CONTROL" title="SBF 배포관리" desc="승인된 변경사항을 새 SBF 버전으로 발행하고 배포 이력을 관리합니다."/><div className="draft-banner"><span>●</span><div><strong>{'미발행 변경사항 '}{pendingCount}{'건'}</strong><p>{pendingCount>0?latestOfficialVersion+' 발행 이후 SBF 반영 완료된 작업본 변경이 있습니다. 새 배포가 필요합니다.':importedThisSession?'이번 세션에서 가져오기로 활성 버전 데이터가 교체되었습니다. 새 배포로 발행할 수 있습니다.':'현재 새로 배포할 SBF 반영 완료 변경이 없습니다.'}</p></div><button onClick={openPublish} disabled={!publishable}>{'새 배포 준비'}</button></div><div className="panel versions"><div className="panel-title"><h2>발행 버전</h2><span>발행일시 내림차순</span></div>{versions.map(x=><article key={x.version}><b>{x.version}</b><div><strong>{x.status}</strong><p>발행일 {x.date} · 발행자 {x.owner} · {x.count.toLocaleString()}개 항목</p></div><span>읽기 전용</span><button onClick={()=>download(x.version)}>⇩ CSV 다운로드</button></article>)}</div>{publish&&<div className="overlay" role="dialog" aria-modal="true"><form className="modal" onKeyDown={blockEnterSubmit} onSubmit={publishVersion}><header><div><small>PUBLISH VERSION</small><h2>새 SBF 배포 발행</h2></div><button type="button" onClick={()=>setPublish(false)}>×</button></header><div className="form-row"><label>버전 번호<input name="versionNo" value={versionInput} onChange={e=>{setVersionInput(e.target.value);setVersionError('')}} placeholder="예: 2.7.1" autoFocus/><small>{'배포할 버전을 입력하세요 (예: 2.7.1)'}</small></label><label>포함 항목<input value={(versions[0]?.count??0).toLocaleString()+'개'} readOnly/></label></div>{versionError&&<p className="import-error" role="alert">{versionError}</p>}<label>발행 사유<textarea name="reason" maxLength={500} placeholder="발행 사유를 입력하세요 (선택)"/></label><p className="immutable-note">현재 활성 공식 버전 데이터를 {(versionInput.trim()||suggestedVersion)} 공식 버전의 불변 스냅샷으로 생성합니다. 기존 {latestOfficialVersion} 버전은 변경하지 않고 보존됩니다.</p><footer><button type="button" onClick={()=>setPublish(false)}>취소</button><button className="primary" disabled={saving||!publishable}>{saving?'배포 중...':'불변 스냅샷 배포'}</button></footer></form></div>}</>
}
export function NotificationPanel({close}:{close:()=>void}){return <div className="notice-panel" role="dialog" aria-modal="true" aria-label="알림함"><header><h2>알림</h2><button onClick={close}>×</button></header><div className="notice-tabs"><button className="active">전체 7</button><button>안읽음 3</button><button>모두 읽음</button></div>{[['보완 요청이 도착했습니다.','CR-2026-0811-03 · 필수 담당자를 확인해 주세요.','3분 전'],['검토자로 배정되었습니다.','CR-2026-0812-07 · 청구계정 업무 Depth 조정','1시간 전'],['Jira 반영에 실패했습니다.','CR-2026-0807-02 · 실패 사유를 확인해 주세요.','어제']].map((x,i)=><article className={i<2?'unread':''} key={x[0]}><i/><div><strong>{x[0]}</strong><p>{x[1]}</p><small>{x[2]}</small></div></article>)}</div>}










