"use client";
import {useState} from "react";
import {items,type Item} from "./data";

const Badge=({text}:{text:string})=><span className={'badge '+(text.includes('완료')||text==='반영'?'green':text.includes('실패')||text.includes('필요')?'orange':'blue')}><i/>{text}</span>;
const Head=({tag,title,desc,children}:{tag:string;title:string;desc:string;children?:React.ReactNode})=><div className="heading"><div><small>{tag}</small><h1>{title}</h1><p>{desc}</p></div><div>{children}</div></div>;

export function HierarchyView({open}:{open:(item:Item)=>void}){
 const [expanded,setExpanded]=useState<string[]>(['1.탐색']);
 const [selected,setSelected]=useState('');
 const depths=[...new Set(items.map(x=>x.d1))];
 const toggle=(key:string)=>setExpanded(x=>x.includes(key)?x.filter(v=>v!==key):[...x,key]);
 return <><Head tag="HIERARCHY" title="SBF 계층 트리" desc="Depth 1~4 구조를 펼쳐 보고 선택한 노드의 업무를 확인합니다."/><div className="tree-layout"><section className="panel tree-panel"><div className="panel-title"><h2>업무 분류체계</h2><span>Depth 1만 기본 펼침</span></div>{depths.map(d1=><div className="tree-node" key={d1}><button className="tree-root" onClick={()=>toggle(d1)}><b>{expanded.includes(d1)?'⌄':'›'}</b><span>{d1}</span><em>{items.filter(x=>x.d1===d1).length}</em></button>{expanded.includes(d1)&&[...new Set(items.filter(x=>x.d1===d1).map(x=>x.d2))].map(d2=><div className="tree-branch" key={d2}><button onClick={()=>toggle(d1+d2)}><b>{expanded.includes(d1+d2)?'−':'+'}</b>{d2}</button>{expanded.includes(d1+d2)&&items.filter(x=>x.d1===d1&&x.d2===d2).map(x=><button key={x.id+'-'+x.sub} className={'tree-leaf '+(selected===x.id+'-'+x.sub?'active':'')} onClick={()=>setSelected(x.id+'-'+x.sub)}><span>{x.d3}</span><small>{x.id} · SUB {x.sub}</small></button>)}</div>)}</div>)}</section><section className="panel tree-results"><div className="panel-title"><h2>선택 노드 업무</h2><span>{selected?'1개':'노드를 선택하세요'}</span></div>{selected?items.filter(x=>x.id+'-'+x.sub===selected).map(x=><article key={selected}><Badge text={x.status}/><h3>{x.d3}</h3><p>{x.d1} › {x.d2} › {x.d3} › {x.d4}</p><dl><dt>업무ID</dt><dd>{x.id} · SUB {x.sub}</dd><dt>L3</dt><dd>{x.l3}</dd><dt>담당 분과</dt><dd>{x.squad}</dd></dl><button className="primary" onClick={()=>open(x)}>상세 정보 보기</button></article>):<div className="empty"><b>⌘</b><h3>계층 노드를 선택해 주세요</h3><p>선택한 업무와 하위 항목이 여기에 표시됩니다.</p></div>}</section></div></>;
}

export function ChangeCompare({request,complete}:{request?:{id:string;title:string;type:string;requester:string;status:string;date:string;note?:string};complete?:()=>void}){const current=request??{id:"CR-2026-0812-07",title:"청구계정 업무 Depth 조정",type:"Depth 조정",requester:"김서현",status:"SBF 반영 중",date:"2026-08-12",note:"SBF 반영 작업 진행 중"};const [after,setAfter]=useState({businessId:"B2036",d1:"2.회원·계정",d2:"청구·납부 계정 관리",d3:"청구계정",d4:"청구계정 정보 관리"});const edit=(key:keyof typeof after,value:string)=>setAfter(x=>({...x,[key]:value}));return <><Head tag="SBF APPLY WORK" title="SBF 반영 작업" desc="승인된 변경요청의 변경 전/후 값을 확인하고 SBF 마스터 반영 값을 직접 수정합니다."><button className="primary" onClick={complete} disabled={!complete||current.status==="SBF 반영 완료"}>{current.status==="SBF 반영 완료"?"반영 완료됨":"SBF 반영 완료"}</button></Head><div className="compare-summary panel"><div><span>요청번호</span><strong>{current.id}</strong></div><div><span>요청 제목</span><strong>{current.title}</strong></div><div><span>요청자</span><strong>{current.requester}</strong></div><div><span>유형</span><strong>{current.type}</strong></div><Badge text={current.status}/></div><div className="apply-guide panel"><strong>SBF 수정 작업 기준</strong><p>변경 요청서의 변경 전/후 내용을 확인한 뒤, 실제 SBF 마스터에 반영할 최종 값을 오른쪽 변경 후 영역에서 수정하세요. 이 화면의 완료 처리는 현재 UI 검증용 상태 변경이며, 실제 DB 반영은 Backend 연결 단계에서 구현됩니다.</p></div><div className="diff-grid sbf-edit-grid"><section className="panel"><div className="diff-title before">변경 전 · v2.5</div><dl><dt>업무ID</dt><dd>B2036</dd><dt>1Depth</dt><dd>2.회원·계정</dd><dt>2Depth</dt><dd>계정 (청구/납부)</dd><dt>3Depth</dt><dd>청구계정</dd><dt>4Depth</dt><dd>청구계정 정보 관리</dd></dl></section><b>→</b><section className="panel"><div className="diff-title after">변경 후 · SBF 수정값</div><dl><dt>업무ID</dt><dd><input aria-label="SBF 수정 업무ID" value={after.businessId} onChange={e=>edit('businessId',e.target.value)}/></dd><dt>1Depth</dt><dd><input aria-label="SBF 수정 1Depth" value={after.d1} onChange={e=>edit('d1',e.target.value)}/></dd><dt>2Depth</dt><dd><input aria-label="SBF 수정 2Depth" value={after.d2} onChange={e=>edit('d2',e.target.value)}/></dd><dt>3Depth</dt><dd><input aria-label="SBF 수정 3Depth" value={after.d3} onChange={e=>edit('d3',e.target.value)}/></dd><dt>4Depth</dt><dd><input aria-label="SBF 수정 4Depth" value={after.d4} onChange={e=>edit('d4',e.target.value)}/></dd></dl></section></div></>}

export function HistoryView(){const [type,setType]=useState('전체');return <><Head tag="AUDITABLE HISTORY" title="SBF 변경이력" desc="필드 단위 변경과 Jira 반영 여부를 시간순으로 추적합니다."></Head><div className="history-layout"><section className="panel history-table"><div className="filters"><label>⌕<input aria-label="변경이력 검색" placeholder="업무ID, 변경 내용 검색"/></label><select aria-label="변경 구분" value={type} onChange={e=>setType(e.target.value)}><option>전체</option><option>업무ID 변경</option><option>Depth 조정</option></select><input type="date" aria-label="시작일" defaultValue="2026-07-01"/><button>조회</button></div><table><thead><tr><th>일자</th><th>변경 구분</th><th>업무ID</th><th>Depth 1</th><th>Depth 2</th><th>Depth 3</th><th>처리자</th><th>Jira</th></tr></thead><tbody>{[['2026-07-15','업무ID 변경','BA451','상품','전략','CR 환경 및 경쟁사 분석','관리자 A','반영'],['2026-07-15','업무ID 변경','BA452','상품','전략','타겟 고객 도출','관리자 A','반영'],['2026-07-08','Depth 조정','B2036','고객','회원·계정','청구계정','관리자 B','미반영']].filter(x=>type==='전체'||x[1]===type).map(x=><tr key={x[2]}>{x.slice(0,7).map((v,i)=><td key={i}>{i===2?<button className="id">{v}</button>:v}</td>)}<td><Badge text={x[7]}/></td></tr>)}</tbody></table></section><aside className="panel timeline"><div className="panel-title"><h2>B2036 타임라인</h2><span>최근 50건</span></div>{[['2026-08-12 10:34','검토 시작','이도윤'],['2026-08-12 09:18','변경요청 접수','김서현'],['2026-07-08 15:42','v2.5 반영 완료','관리자 B']].map((x,i)=><div key={x[0]}><i className={i===0?'active':''}/><p><strong>{x[1]}</strong><small>{x[0]} · {x[2]}</small></p></div>)}</aside></div></>}

export function VersionView({download,notify,pendingCount}:{download:(v:string)=>void;notify:(x:string)=>void;pendingCount:number}){
 const snapshotMode="Netlify prototype snapshot";const [publish,setPublish]=useState(false),[saving,setSaving]=useState(false);
 const publishVersion=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget),versionNo=String(data.get('versionNo')??'v2.6');setSaving(true);setTimeout(()=>{setSaving(false);setPublish(false);notify(versionNo+' \uBD88\uBCC0 \uC2A4\uB0C5\uC0F7\uC744 \uBC30\uD3EC \uAC80\uD1A0\uC6A9\uC73C\uB85C \uC0DD\uC131\uD588\uC2B5\uB2C8\uB2E4. Netlify \uBC30\uD3EC\uBCF8\uC740 UI \uAC80\uC99D\uC6A9 \uC0C1\uD0DC\uB85C \uB3D9\uC791\uD569\uB2C8\uB2E4.')},350)};
 return <><Head tag="DEPLOYMENT CONTROL" title="SBF 배포관리" desc="승인된 변경사항을 새 SBF 버전으로 발행하고 배포 이력을 관리합니다."><button className="primary" onClick={()=>setPublish(true)}>{'\u002B \uC0C8 \uBC30\uD3EC'}</button></Head><div className="draft-banner"><span>●</span><div><strong>{'\uBBF8\uBC1C\uD589 \uBCC0\uACBD\uC0AC\uD56D '}{pendingCount}{'\uAC74'}</strong><p>{pendingCount>0?'v2.5 \uBC1C\uD589 \uC774\uD6C4 \uC2B9\uC778\uB41C \uBCC0\uACBD\uC774 \uC788\uC2B5\uB2C8\uB2E4. \uC0C8 \uBC30\uD3EC\uAC00 \uD544\uC694\uD569\uB2C8\uB2E4.':'\uD604\uC7AC \uC0C8\uB85C \uBC30\uD3EC\uD560 \uC2B9\uC778 \uBCC0\uACBD\uC774 \uC5C6\uC2B5\uB2C8\uB2E4.'}</p></div><button onClick={()=>setPublish(true)} disabled={pendingCount===0}>v2.6 {'\uBC30\uD3EC \uC900\uBE44'}</button></div><div className="panel versions"><div className="panel-title"><h2>발행 버전</h2><span>발행일시 내림차순</span></div>{[['v2.5','2026-08-10 09:00','김서현','1,172','현재 활성'],['v2.4','2026-07-18 14:05','관리자 A','1,182','이전 버전']].map(x=><article key={x[0]}><b>{x[0]}</b><div><strong>{x[4]}</strong><p>발행일 {x[1]} · 발행자 {x[2]} · {x[3]}개 항목</p></div><span>읽기 전용</span><button onClick={()=>download(x[0])}>⇩ CSV 다운로드</button></article>)}</div>{publish&&<div className="overlay" role="dialog" aria-modal="true"><form className="modal" onSubmit={publishVersion}><header><div><small>PUBLISH VERSION</small><h2>새 SBF 배포 발행</h2></div><button type="button" onClick={()=>setPublish(false)}>×</button></header><div className="form-row"><label>버전 번호<select name="versionNo"><option value="v2.6">자동 증가 · v2.6</option><option value="v3.0">직접 입력 예시 · v3.0</option></select></label><label>포함 항목<input value="1,199개" readOnly/></label></div><label>발행 사유<textarea name="reason" maxLength={500} placeholder="발행 사유를 입력하세요 (선택)"/></label><p className="immutable-note">발행된 스냅샷은 수정할 수 없으며 이후 변경은 새 Draft로 관리됩니다.</p><footer><button type="button" onClick={()=>setPublish(false)}>취소</button><button className="primary" disabled={saving||pendingCount===0}>{saving?'\uBC30\uD3EC \uC911...':'\uBD88\uBCC0 \uC2A4\uB0C5\uC0F7 \uBC30\uD3EC'}</button></footer></form></div>}</>
}
export function NotificationPanel({close}:{close:()=>void}){return <div className="notice-panel" role="dialog" aria-modal="true" aria-label="알림함"><header><h2>알림</h2><button onClick={close}>×</button></header><div className="notice-tabs"><button className="active">전체 7</button><button>안읽음 3</button><button>모두 읽음</button></div>{[['보완 요청이 도착했습니다.','CR-2026-0811-03 · 필수 담당자를 확인해 주세요.','3분 전'],['검토자로 배정되었습니다.','CR-2026-0812-07 · 청구계정 업무 Depth 조정','1시간 전'],['Jira 반영에 실패했습니다.','CR-2026-0807-02 · 실패 사유를 확인해 주세요.','어제']].map((x,i)=><article className={i<2?'unread':''} key={x[0]}><i/><div><strong>{x[0]}</strong><p>{x[1]}</p><small>{x[2]}</small></div></article>)}</div>}




