"use client";
import {useState} from "react";
import {items,requests,type Item} from "./data";

const Badge=({text}:{text:string})=><span className={'badge '+(text.includes('완료')||text==='반영'?'green':text.includes('실패')||text.includes('필요')?'orange':'blue')}><i/>{text}</span>;
const Head=({tag,title,desc,children}:{tag:string;title:string;desc:string;children?:React.ReactNode})=><div className="heading"><div><small>{tag}</small><h1>{title}</h1><p>{desc}</p></div><div>{children}</div></div>;

export function HierarchyView({open}:{open:(item:Item)=>void}){
 const [expanded,setExpanded]=useState<string[]>(['1.탐색']);
 const [selected,setSelected]=useState('');
 const depths=[...new Set(items.map(x=>x.d1))];
 const toggle=(key:string)=>setExpanded(x=>x.includes(key)?x.filter(v=>v!==key):[...x,key]);
 return <><Head tag="HIERARCHY" title="SBF 계층 트리" desc="Depth 1~4 구조를 펼쳐 보고 선택한 노드의 업무를 확인합니다."/><div className="tree-layout"><section className="panel tree-panel"><div className="panel-title"><h2>업무 분류체계</h2><span>Depth 1만 기본 펼침</span></div>{depths.map(d1=><div className="tree-node" key={d1}><button className="tree-root" onClick={()=>toggle(d1)}><b>{expanded.includes(d1)?'⌄':'›'}</b><span>{d1}</span><em>{items.filter(x=>x.d1===d1).length}</em></button>{expanded.includes(d1)&&[...new Set(items.filter(x=>x.d1===d1).map(x=>x.d2))].map(d2=><div className="tree-branch" key={d2}><button onClick={()=>toggle(d1+d2)}><b>{expanded.includes(d1+d2)?'−':'+'}</b>{d2}</button>{expanded.includes(d1+d2)&&items.filter(x=>x.d1===d1&&x.d2===d2).map(x=><button key={x.id+'-'+x.sub} className={'tree-leaf '+(selected===x.id+'-'+x.sub?'active':'')} onClick={()=>setSelected(x.id+'-'+x.sub)}><span>{x.d3}</span><small>{x.id} · SUB {x.sub}</small></button>)}</div>)}</div>)}</section><section className="panel tree-results"><div className="panel-title"><h2>선택 노드 업무</h2><span>{selected?'1개':'노드를 선택하세요'}</span></div>{selected?items.filter(x=>x.id+'-'+x.sub===selected).map(x=><article key={selected}><Badge text={x.status}/><h3>{x.d3}</h3><p>{x.d1} › {x.d2} › {x.d3} › {x.d4}</p><dl><dt>업무ID</dt><dd>{x.id} · SUB {x.sub}</dd><dt>L3</dt><dd>{x.l3}</dd><dt>담당 분과</dt><dd>{x.squad}</dd></dl><button className="primary" onClick={()=>open(x)}>상세 정보 보기</button></article>):<div className="empty"><b>⌘</b><h3>계층 노드를 선택해 주세요</h3><p>선택한 업무와 하위 항목이 여기에 표시됩니다.</p></div>}</section></div></>;
}

export function ChangeCompare(){return <><Head tag="REVIEW" title="변경 전후 비교" desc="요청 항목별 변경값과 계층 이동을 비교하고 검토합니다."><button>검토 의견</button><button className="primary">승인</button></Head><div className="compare-summary panel"><div><span>요청번호</span><strong>CR-2026-0812-07</strong></div><div><span>요청자</span><strong>김서현 · SBF 기획</strong></div><div><span>유형</span><strong>Depth 조정</strong></div><Badge text="검토 중"/></div><div className="diff-grid"><section className="panel"><div className="diff-title before">변경 전 · v2.5</div><dl><dt>업무ID</dt><dd>B2036</dd><dt>1Depth</dt><dd>2.회원·계정</dd><dt>2Depth</dt><dd className="changed">계정 (청구/납부)</dd><dt>3Depth</dt><dd>청구계정</dd><dt>4Depth</dt><dd>청구계정 정보 관리</dd></dl></section><b>→</b><section className="panel"><div className="diff-title after">변경 후 · 미발행 Draft</div><dl><dt>업무ID</dt><dd>B2036</dd><dt>1Depth</dt><dd>2.회원·계정</dd><dt>2Depth</dt><dd className="changed">청구·납부 계정 관리</dd><dt>3Depth</dt><dd>청구계정</dd><dt>4Depth</dt><dd>청구계정 정보 관리</dd></dl></section></div><div className="panel depth-move"><div className="panel-title"><h2>계층 이동 미리보기</h2><span>변경 필드 1개</span></div><div><span>2.회원·계정</span><b>›</b><del>계정 (청구/납부)</del><b>→</b><ins>청구·납부 계정 관리</ins><b>›</b><span>청구계정</span></div></div></>}

export function HistoryView(){const [type,setType]=useState('전체');return <><Head tag="AUDITABLE HISTORY" title="SBF 변경이력" desc="필드 단위 변경과 Jira 반영 여부를 시간순으로 추적합니다."><button>⇩ CSV</button></Head><div className="history-layout"><section className="panel history-table"><div className="filters"><label>⌕<input aria-label="변경이력 검색" placeholder="업무ID, 변경 내용 검색"/></label><select aria-label="변경 구분" value={type} onChange={e=>setType(e.target.value)}><option>전체</option><option>업무ID 변경</option><option>Depth 조정</option></select><input type="date" aria-label="시작일" defaultValue="2026-07-01"/><button>조회</button></div><table><thead><tr><th>일자</th><th>변경 구분</th><th>업무ID</th><th>Depth 1</th><th>Depth 2</th><th>Depth 3</th><th>처리자</th><th>Jira</th></tr></thead><tbody>{[['2026-07-15','업무ID 변경','BA451','상품','전략','CR 환경 및 경쟁사 분석','관리자 A','반영'],['2026-07-15','업무ID 변경','BA452','상품','전략','타겟 고객 도출','관리자 A','반영'],['2026-07-08','Depth 조정','B2036','고객','회원·계정','청구계정','관리자 B','미반영']].filter(x=>type==='전체'||x[1]===type).map(x=><tr key={x[2]}>{x.slice(0,7).map((v,i)=><td key={i}>{i===2?<button className="id">{v}</button>:v}</td>)}<td><Badge text={x[7]}/></td></tr>)}</tbody></table></section><aside className="panel timeline"><div className="panel-title"><h2>B2036 타임라인</h2><span>최근 50건</span></div>{[['2026-08-12 10:34','검토 시작','이도윤'],['2026-08-12 09:18','변경요청 접수','김서현'],['2026-07-08 15:42','v2.5 반영 완료','관리자 B']].map((x,i)=><div key={x[0]}><i className={i===0?'active':''}/><p><strong>{x[1]}</strong><small>{x[0]} · {x[2]}</small></p></div>)}</aside></div></>}

export function JiraView(){return <><Head tag="JIRA TRACKING" title="Jira 반영 관리" desc="작업 완료 건의 Jira 미반영·실패·완료 상태를 관리합니다."><button className="primary">반영 상태 등록</button></Head><div className="stats">{[['J','미반영','9','확인 필요','orange'],['↻','반영 실패','2','재처리 대기','violet'],['✓','이번 달 반영','26','정상 완료','green']].map(x=><div key={x[1]}><span className={x[4]}>{x[0]}</span><p>{x[1]}<strong>{x[2]}</strong><small>{x[3]}</small></p></div>)}</div><div className="panel requests"><table><thead><tr><th>요청번호</th><th>변경 제목</th><th>작업 완료일</th><th>담당자</th><th>Jira 이슈</th><th>상태</th><th>작업</th></tr></thead><tbody>{requests.slice(0,3).map((x,i)=><tr key={x[0]}><td><button className="id">{x[0]}</button></td><td><strong>{x[1]}</strong></td><td>{x[5]}</td><td>{x[3]}</td><td>{i===2?'SBF-2841':'—'}</td><td><Badge text={i===2?'반영 완료':i===1?'반영 실패':'미반영'}/></td><td><button>{i===2?'이슈 열기':'상태 입력'}</button></td></tr>)}</tbody></table></div></>}

export function VersionView({download,notify}:{download:(v:string)=>void;notify:(x:string)=>void}){const [publish,setPublish]=useState(false);return <><Head tag="VERSION CONTROL" title="SBF 버전 관리" desc="발행된 불변 스냅샷을 조회·다운로드하고 현재 Draft를 새 버전으로 발행합니다."><button className="primary" onClick={()=>setPublish(true)}>＋ 새 버전 발행</button></Head><div className="draft-banner"><span>●</span><div><strong>미발행 변경사항 27건</strong><p>v2.5 발행 이후 승인된 변경이 있습니다. 새 버전 발행이 필요합니다.</p></div><button onClick={()=>setPublish(true)}>v2.6 발행 준비</button></div><div className="panel versions"><div className="panel-title"><h2>발행 버전</h2><span>발행일시 내림차순</span></div>{[['v2.5','2026-08-10 09:00','김서현','1,172','현재 활성'],['v2.4','2026-07-18 14:05','관리자 A','1,182','이전 버전']].map(x=><article key={x[0]}><b>{x[0]}</b><div><strong>{x[4]}</strong><p>발행일 {x[1]} · 발행자 {x[2]} · {x[3]}개 항목</p></div><span>읽기 전용</span><button onClick={()=>download(x[0])}>⇩ CSV 다운로드</button></article>)}</div>{publish&&<div className="overlay" role="dialog" aria-modal="true"><form className="modal" onSubmit={e=>{e.preventDefault();setPublish(false);notify('v2.6 발행 작업을 생성했습니다.')}}><header><div><small>PUBLISH VERSION</small><h2>새 SBF 버전 발행</h2></div><button type="button" onClick={()=>setPublish(false)}>×</button></header><div className="form-row"><label>버전 번호<select><option>자동 증가 · v2.6</option><option>직접 입력</option></select></label><label>포함 항목<input value="1,199개" readOnly/></label></div><label>발행 사유<textarea maxLength={500} placeholder="발행 사유를 입력하세요 (선택)"/></label><p className="immutable-note">발행된 스냅샷은 수정할 수 없으며 이후 변경은 새 Draft로 관리됩니다.</p><footer><button type="button" onClick={()=>setPublish(false)}>취소</button><button className="primary">불변 스냅샷 발행</button></footer></form></div>}</>}

export function AuditView(){return <><Head tag="GOVERNANCE" title="감사 로그" desc="중요 행위의 수행자·시각·대상·결과를 변경 불가능한 로그로 조회합니다."/><div className="panel requests"><div className="filters"><label>⌕<input aria-label="감사로그 검색" placeholder="수행자, 업무ID, 행위 검색"/></label><select><option>전체 행위</option><option>변경 승인</option><option>버전 발행</option></select><input type="date" defaultValue="2026-08-01"/><button>조회</button></div><table><thead><tr><th>일시</th><th>수행자</th><th>역할</th><th>행위</th><th>대상</th><th>결과</th><th>상관 ID</th></tr></thead><tbody>{[['2026-08-12 10:34','이도윤','Reviewer','검토 시작','CR-2026-0812-07','성공','AUD-91F2'],['2026-08-12 09:18','김서현','Requester','요청 제출','B2036','성공','AUD-91E8'],['2026-08-10 09:00','김서현','SBF Admin','버전 발행','SBF v2.5','성공','AUD-8FC1']].map(x=><tr key={x[6]}>{x.map((v,i)=><td key={i}>{i===5?<Badge text={v}/>:v}</td>)}</tr>)}</tbody></table></div></>}

export function NotificationPanel({close}:{close:()=>void}){return <div className="notice-panel" role="dialog" aria-modal="true" aria-label="알림함"><header><h2>알림</h2><button onClick={close}>×</button></header><div className="notice-tabs"><button className="active">전체 7</button><button>안읽음 3</button><button>모두 읽음</button></div>{[['보완 요청이 도착했습니다.','CR-2026-0811-03 · 필수 담당자를 확인해 주세요.','3분 전'],['검토자로 배정되었습니다.','CR-2026-0812-07 · 청구계정 업무 Depth 조정','1시간 전'],['Jira 반영에 실패했습니다.','CR-2026-0807-02 · 실패 사유를 확인해 주세요.','어제']].map((x,i)=><article className={i<2?'unread':''} key={x[0]}><i/><div><strong>{x[0]}</strong><p>{x[1]}</p><small>{x[2]}</small></div></article>)}</div>}